# Generated by Django 5.2.5 on 2025-08-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoteCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produtor', models.CharField(max_length=100, verbose_name='Nome do produtor')),
                ('nome_chacara', models.CharField(max_length=100, verbose_name='Nome da chácara')),
                ('data_plantio', models.DateField(verbose_name='Data do plantio')),
                ('tipo_grao', models.CharField(max_length=50, verbose_name='Tipo do grão')),
                ('data_colheita', models.DateField(verbose_name='Data da colheita')),
                ('tipo_processamento', models.CharField(max_length=100, verbose_name='Tipo de processamento')),
                ('data_lavagem', models.DateField(verbose_name='Data da lavagem')),
                ('data_secagem', models.DateField(verbose_name='Data da secagem')),
                ('data_pilagem', models.DateField(verbose_name='Data da pilagem')),
                ('data_torrefacao', models.DateField(verbose_name='Data da torrefação')),
                ('data_embalagem', models.DateField(verbose_name='Data da embalagem')),
                ('data_validade', models.DateField(verbose_name='Data de validade')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
            ],
        ),
    ]
