# Generated by Django 5.2.5 on 2025-08-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreabilidade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotecafe',
            name='criado_em',
        ),
        migrations.AddField(
            model_name='lotecafe',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='lotes/'),
        ),
        migrations.AddField(
            model_name='lotecafe',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='lotecafe',
            name='data_colheita',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lotecafe',
            name='data_embalagem',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lotecafe',
            name='data_lavagem',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lotecafe',
            name='data_pilagem',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lotecafe',
            name='data_plantio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lotecafe',
            name='data_secagem',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lotecafe',
            name='data_torrefacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lotecafe',
            name='data_validade',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lotecafe',
            name='nome_chacara',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lotecafe',
            name='nome_produtor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lotecafe',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lotecafe',
            name='tipo_grao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lotecafe',
            name='tipo_processamento',
            field=models.CharField(max_length=50),
        ),
    ]
