# Generated by Django 5.2.5 on 2025-09-22 21:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreabilidade', '0002_remove_lotecafe_criado_em_lotecafe_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotecafe',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='lotecafe',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
