# Generated by Django 5.2.5 on 2025-09-22 22:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreabilidade', '0003_remove_lotecafe_qr_code_lotecafe_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecafe',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
